# Generated by Django 5.2.3 on 2025-07-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcuser',
            options={'verbose_name': '솔데스크 사용자', 'verbose_name_plural': '솔데스크 사용자'},
        ),
        migrations.AddField(
            model_name='bcuser',
            name='useremail',
            field=models.EmailField(default='test@email.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
