# Generated by Django 5.2.3 on 2025-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0002_alter_bcuser_options_bcuser_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
