# Generated by Django 5.2.3 on 2025-07-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bcuser', '0003_alter_bcuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcuser.bcuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '솔데스크캠퍼스 게시글',
                'verbose_name_plural': '솔데스크캠퍼스 게시글',
                'db_table': 'bootcampus_board',
            },
        ),
    ]
